import 'package:jiburo_app/models/find_pets_model.dart';

class PostDemoList {
  static List<FindPetsModel> pets = [
    FindPetsModel(
      id: "1",
      name: '복돌이',
      writer: '레이맘',
      title: "복돌이를 찾아주세요",
      breeds: '강아지',
      missingSpot: '서울시 강동구 천호동',
      area: '5',
      reward: '30',
      time: '1',
      imgPath: 'assets/images/1.jpg',
      isLike: true,
    ),
    FindPetsModel(
      id: "2",
      name: '아로',
      writer: '작성자',
      title: "아로를 찾아주세요",
      breeds: '강아지',
      missingSpot: '서울시 강동구 길동',
      area: '3',
      reward: '30',
      time: '3',
      imgPath: 'assets/images/2.png',
      isLike: false,
    ),
    FindPetsModel(
      id: "3",
      name: '영숙이',
      writer: '작성자',
      title: "제목을 입력하세요",
      breeds: '고양이',
      missingSpot: '서울시 강동구 명일동',
      area: '2',
      reward: '50',
      time: '5',
      imgPath: 'assets/images/4.png',
      isLike: false,
    ),
    FindPetsModel(
      id: "4",
      name: '복돌이',
      writer: '작성자',
      title: "제목을 입력하세요",
      breeds: '강아지',
      missingSpot: '서울시 강동구 천호동',
      area: '5',
      reward: '30',
      time: '1',
      imgPath: 'assets/images/5.png',
      isLike: true,
    ),
    FindPetsModel(
      id: "5",
      name: '아로',
      writer: '작성자',
      title: "제목을 입력하세요",
      breeds: '강아지',
      missingSpot: '서울시 강동구 길동',
      area: '3',
      reward: '30',
      time: '3',
      imgPath: 'assets/images/2.png',
      isLike: false,
    ),
    FindPetsModel(
      id: "6",
      name: '레이',
      writer: '작성자',
      title: "제목을 입력하세요",
      breeds: '고양이',
      missingSpot: '서울시 강동구 고덕동',
      area: '1',
      reward: '20',
      time: '5',
      imgPath: 'assets/images/3.jpg',
      isLike: false,
    ),
    FindPetsModel(
      id: "7",
      name: '복돌이',
      writer: '작성자',
      title: "제목을 입력하세요",
      breeds: '강아지',
      missingSpot: '서울시 강동구 천호동',
      area: '5',
      reward: '30',
      time: '1',
      imgPath: 'assets/images/1.jpg',
      isLike: true,
    ),
    FindPetsModel(
      id: "8",
      name: '아로',
      writer: '작성자',
      title: "제목을 입력하세요",
      breeds: '강아지',
      missingSpot: '서울시 강동구 길동',
      area: '3',
      reward: '30',
      time: '3',
      imgPath: 'assets/images/2.png',
      isLike: false,
    ),
    FindPetsModel(
      id: "9",
      name: '레이',
      writer: '작성자',
      title: "제목을 입력하세요",
      breeds: '고양이',
      missingSpot: '서울시 강동구 고덕동',
      area: '1',
      reward: '20',
      time: '5',
      imgPath: 'assets/images/3.jpg',
      isLike: false,
    ),
  ];
}
